version : "3"
services:
  online-compiler-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-compiler-api
    depends_on:
      - online-compiler-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2100:80"
      - "2101:2101"
    environment:
      APP_NAME: 'Laravel Boilerplate for 10x developers'
      APP_DEBUG: 'true'
      APP_URL: 'http://100.102.1.1'
      DB_CONNECTION: 'pgsql'
      QUEUE_CONNECTION: 'database'
      XDEBUG_CONFIG: "mode=debug,coverage,develop client_host=host.docker.internal discover_client_host=1 start_with_request=yes"
      GITHUB_USERNAME: 'jdecode'
      GITHUB_REPONAME: 'online-compiler'
    networks:
      online-compiler-api-network:
        ipv4_address: 100.102.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  online-compiler-pg:
    image: postgres:latest
    ports:
        - "2110:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test_db
    container_name: online-compiler-pg
    volumes:
      - online-compiler-pg-disk:/var/lib/postgres
    networks:
      online-compiler-api-network:
        ipv4_address: 100.102.1.2

  online-compiler-tf:
      build:
        context: .
        dockerfile: terraform/Dockerfile
      container_name: online-compiler-tf
      volumes:
          - .:/var/www/html
      environment:
        HEROKU_API_KEY: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
        AWS_ACCESS_KEY_ID: 'xxxxxxxxxxxxxxxxxxxx'
        AWS_SECRET_ACCESS_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        POSTMAN_API_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        CIRCLECI_API_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

      networks:
        online-compiler-api-network:
          ipv4_address: 100.102.1.3

# On-disk storage of DB data, when containers are stopped
volumes:
  online-compiler-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  online-compiler-api-network:
    ipam:
      driver: default
      config:
        - subnet: 100.102.0.0/16
